"""Search: structured proposal schemas, evidence-driven feedback, and the archive.

Phase 4 of ``spec.md`` turns evolution into testable edits: every proposal states
a hypothesis and a prediction that can be wrong, every attempted candidate leaves
a record, and the archive keeps a simple and a behaviourally distinct candidate
alongside the best one.
"""

from lares.search.archive import (
    SLOT_DISTINCT,
    SLOT_ROBUST,
    SLOT_SIMPLEST,
    SLOTS,
    Archive,
    ArchiveEntry,
    behavior_descriptor,
    behavioral_distance,
)
from lares.search.feedback import (
    LOSS_CAVEAT,
    CandidateEvidence,
    build_feedback,
    choose_informative_parents,
    diagnostics_block,
    population_table,
)
from lares.search.schemas import (
    BOUNDED_MODES,
    MODE_CROSSOVER,
    MODE_EXPLORATION,
    MODE_PARAMETER_ONLY,
    MODE_REPAIR,
    MODE_SIMPLIFICATION,
    MUTATION_MODES,
    PARAM_GAIN,
    PARAM_STRUCTURAL,
    PARAMETER_TYPES,
    STATUS_EVALUATED,
    STATUS_FITTED,
    STATUS_GENERATED,
    STATUS_INVALID,
    STATUS_PROMOTED,
    STATUS_REJECTED,
    STATUSES,
    ExperimentRecord,
    IdeaParameter,
    IdeaPhase,
    MutationProposal,
    PolicyIdea,
    SchemaError,
    load_records,
    measurable_metrics,
    source_hash,
)

__all__ = [
    "Archive",
    "ArchiveEntry",
    "BOUNDED_MODES",
    "CandidateEvidence",
    "ExperimentRecord",
    "IdeaParameter",
    "IdeaPhase",
    "LOSS_CAVEAT",
    "MODE_CROSSOVER",
    "MODE_EXPLORATION",
    "MODE_PARAMETER_ONLY",
    "MODE_REPAIR",
    "MODE_SIMPLIFICATION",
    "MUTATION_MODES",
    "MutationProposal",
    "PARAMETER_TYPES",
    "PARAM_GAIN",
    "PARAM_STRUCTURAL",
    "PolicyIdea",
    "SLOTS",
    "SLOT_DISTINCT",
    "SLOT_ROBUST",
    "SLOT_SIMPLEST",
    "STATUSES",
    "STATUS_EVALUATED",
    "STATUS_FITTED",
    "STATUS_GENERATED",
    "STATUS_INVALID",
    "STATUS_PROMOTED",
    "STATUS_REJECTED",
    "SchemaError",
    "behavior_descriptor",
    "behavioral_distance",
    "build_feedback",
    "choose_informative_parents",
    "diagnostics_block",
    "load_records",
    "measurable_metrics",
    "population_table",
    "source_hash",
]
