"""Numerical fitting: the frozen structure bank, optimizers, and sensitivity.

Phase 3 of ``spec.md`` separates structure search from parameter fitting, so a
structure is never rejected because one optimizer run from one initialisation
happened to fail.
"""

from lares.fitting.optimizers import (
    ADAM_BASELINE,
    ADAM_SCALED,
    CHECKPOINT_BEST_VALIDATION,
    CHECKPOINT_FINAL,
    CHECKPOINT_RULES,
    DIFFERENTIAL_EVOLUTION,
    METHODS,
    MULTISTART_ADAM,
    FitResult,
    FittingData,
    bc_objective,
    fit,
    perturb_within_ranges,
    prepare_data,
)
from lares.fitting.dagger import (
    AggregationStats,
    aggregate_learner_states,
    validate_expert_label,
)
from lares.fitting.objectives import (
    CENSORED_GAUSSIAN,
    DETERMINISTIC_MSE,
    EXEC_CLIPPED_DETERMINISTIC,
    EXEC_CLIPPED_GAUSSIAN,
    EXEC_DETERMINISTIC_TANH,
    EXEC_TANH_GAUSSIAN,
    EXECUTION_CONTRACTS,
    LEGACY_MSE_STD_PENALTY,
    OBJECTIVES,
    RESIDUAL_SCALE,
    TANH_GAUSSIAN_NLL,
    ObjectiveSpec,
    censored_fraction,
    check_execution_matches,
    execute,
    find_scale_parameters,
    freeze_scale_parameters,
    objective_loss,
    spec,
    trainable_parameters,
)
from lares.fitting.phases import (
    PHASE_NAMES,
    balanced_indices,
    expert_phase_labels,
    phase_counts,
    phase_fractions,
    verify_against_expert,
)
from lares.fitting.sensitivity import (
    action_sensitivity,
    dead_parameters,
    gradient_sensitivity,
    summarise_sensitivity,
)
from lares.fitting.structure_bank import (
    SIMPLE_FAMILY_MAX_PARAMS,
    STRUCTURES_DIR,
    Structure,
    check_port_equivalence,
    instantiate_source,
    load_bank,
    load_structure,
    port_raw_indices,
    summarise_bank,
)

__all__ = [
    "ADAM_BASELINE",
    "AggregationStats",
    "CENSORED_GAUSSIAN",
    "DETERMINISTIC_MSE",
    "EXECUTION_CONTRACTS",
    "EXEC_CLIPPED_DETERMINISTIC",
    "EXEC_CLIPPED_GAUSSIAN",
    "EXEC_DETERMINISTIC_TANH",
    "EXEC_TANH_GAUSSIAN",
    "LEGACY_MSE_STD_PENALTY",
    "OBJECTIVES",
    "ObjectiveSpec",
    "PHASE_NAMES",
    "RESIDUAL_SCALE",
    "TANH_GAUSSIAN_NLL",
    "aggregate_learner_states",
    "balanced_indices",
    "censored_fraction",
    "check_execution_matches",
    "execute",
    "expert_phase_labels",
    "find_scale_parameters",
    "freeze_scale_parameters",
    "objective_loss",
    "phase_counts",
    "phase_fractions",
    "spec",
    "trainable_parameters",
    "validate_expert_label",
    "verify_against_expert",
    "ADAM_SCALED",
    "CHECKPOINT_BEST_VALIDATION",
    "CHECKPOINT_FINAL",
    "CHECKPOINT_RULES",
    "DIFFERENTIAL_EVOLUTION",
    "METHODS",
    "MULTISTART_ADAM",
    "SIMPLE_FAMILY_MAX_PARAMS",
    "STRUCTURES_DIR",
    "FitResult",
    "FittingData",
    "Structure",
    "action_sensitivity",
    "bc_objective",
    "check_port_equivalence",
    "dead_parameters",
    "fit",
    "gradient_sensitivity",
    "instantiate_source",
    "load_bank",
    "load_structure",
    "perturb_within_ranges",
    "port_raw_indices",
    "prepare_data",
    "summarise_bank",
    "summarise_sensitivity",
]
